theme = "nightfox"

[editor.soft-wrap]
enable = true

[keys.normal]
space.B = ":echo %sh{git log -L %{cursor_line},+1:%{buffer_name} -1 -s --pretty=format:'%%h (%%an %%ai %{cursor_line}) %%s'}"
C-s = "hsplit"
C-v = "vsplit"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"

[keys.select]
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"
